parameters:
    VDM.host: 'viedemerde.fr'
    VDM.limit: 40;

services:
    iadvize_site_crawler:
        class: Iadvize\BlogBundle\Component\VdmSitecrawler
        #@service_id, "plain_value",#
        arguments: [%VDM.host%, %VDM.limit%, @doctrine.orm.entity_manager]
